[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
#type = "database"
type = "database_unique_id"
read_groups = true

[configuration.store.query_length]
max="4194304"

[encryption]
key = "<provide-your-key-here>"
internal_crypto_provider = "org.wso2.carbon.crypto.provider.KeyStoreBasedInternalCryptoProvider"

[system_applications]
read_only_apps = []

[system.parameter]
"org.wso2.CipherTransformation"="RSA/ECB/OAEPwithSHA1andMGF1Padding"


# MSSQL CONFIGS

[database.user]
url = "jdbc:sqlserver://localhost:1433;databaseName=testdb;SendStringParametersAsUnicode=false"
username = "SA"
password = "YourStrongPassw0rd"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[realm_manager]
data_source = "WSO2USER_DB"

[database.identity_db]
url = "jdbc:sqlserver://localhost:1433;databaseName=testdb;SendStringParametersAsUnicode=false"
username = "SA"
password = "YourStrongPassw0rd"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[database.identity_db.pool_options]
maxActive = "80"
maxWait="6000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
url = "jdbc:sqlserver://localhost:1433;databaseName=testdb;SendStringParametersAsUnicode=false"
username = "SA"
password = "YourStrongPassw0rd"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
[database.shared_db.pool_options]
maxActive = "80"
maxWait="6000"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[[datasource]]
id="WSO2CONSENT_DB"
url = "jdbc:sqlserver://localhost:1433;databaseName=testdb;SendStringParametersAsUnicode=false"
username = "SA"
password = "YourStrongPassw0rd"
driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver"
jmx_enable=false


#[bps_database.config]
#url = "jdbc:mysql://localhost:3306/testdb?useSSL=false"
#username = "root"
#password = "root"
#driver = "com.mysql.jdbc.Driver"

[keystore.primary]
file_name = "wso2carbon.jks"
password = "wso2carbon"

[truststore]
file_name="client-truststore.jks"
password="wso2carbon"
type="JKS"

[account_recovery.endpoint.auth]
hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

[identity.auth_framework.endpoint]
app_password= "dashboard"

#Remove Unused Tokens from the Database

#[oauth.token_cleanup]
#enable = false

#### Depending on your database, select the appropriate token cleanup script based on the links mentioned in the link below ### 
#https://is.docs.wso2.com/en/latest/deploy/remove-unused-tokens-from-the-database/#use-the-store-procedure-for-token-cleanup

#[oauth.token_cleanup]
#enable = true
#retain_access_tokens_for_auditing = true

#https://github.com/wso2/carbon-identity-framework/tree/master/features/identity-core/org.wso2.carbon.identity.core.server.feature/resources/dbscripts/stored-procedures/mysql/token-cleanup

# The KeyStore which is used for encrypting/decrypting internal data. By default the primary keystore is used as the internal keystore.

#[keystore.internal]
#file_name = "$ref{keystore.primary.file_name}"
#type = "$ref{keystore.primary.type}"
#password = "$ref{keystore.primary.password}"
#alias = "$ref{keystore.primary.alias}"
#key_password = "$ref{keystore.primary.key_password}"

# The KeyStore which is used for tls communication. By default the primary keystore is used as the tls keystore.

#[keystore.tls]
#file_name = "$ref{keystore.primary.file_name}"
#type = "$ref{keystore.primary.type}"
#password = "$ref{keystore.primary.password}"
#alias = "$ref{keystore.primary.alias}"
#key_password = "$ref{keystore.primary.key_password}"

#Google reCAPTCHA settings.

#[recaptcha]
#enabled = "true"
#api_url = "https://www.google.com/recaptcha/api.js"
#verify_url = "https://www.google.com/recaptcha/api/siteverify"
#site_key = ""
#secret_key = ""

# SMTP email sender settings.
#[output_adapter.email]
#from_address= "abcd@gmail.com"
#username= "abcd"
#password= "xxxx"
#hostname= "smtp.gmail.com"
#port= 587
