[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database"
read_groups = true

[user_store.properties]
SCIMEnabled= true

[admin_service.wsdl]
enable = true

# MYSQL CONFIGS

[admin_service.wsdl]
enable = true

[database.user]
url = "jdbc:mysql://localhost:3306/mydb?useSSL=false&amp;allowPublicKeyRetrieval=true"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"

[realm_manager]
data_source = "WSO2USER_DB"

[database.identity_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/mydb?useSSL=false&amp;allowPublicKeyRetrieval=true"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"
[database.identity_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[database.shared_db]
type = "mysql"
url = "jdbc:mysql://localhost:3306/mydb?useSSL=false&amp;allowPublicKeyRetrieval=true"
username = "root"
password = "root"
driver = "com.mysql.jdbc.Driver"
[database.shared_db.pool_options]
maxActive = "80"
minIdle ="5"
testOnBorrow = true
validationQuery="SELECT 1"
validationInterval="30000"
defaultAutoCommit=false

[keystore.primary]
name = "wso2carbon.jks"
password = "wso2carbon"

#url = "jdbc:mysql://localhost:3306/mydb?useSSL=false"
