name: Ubuntu Postgres Setup

on:
  workflow_run:
    workflows: ["Composite Workflow 🐧🍎🪟"]
    types:
      - completed

jobs:
  setup-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Checkout code
        uses: actions/checkout@v2
      - name: 🐳 Setup Docker environment
        run: |
          # Update and upgrade packages, and install necessary dependencies
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          # Add Docker GPG key and add the Docker repository
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          # Update the packages again and install Docker CE
          sudo apt-get update
          sudo apt-get install -y docker-ce
      - name: 🐋 Run Docker command
        run: |
          # Create the PostgreSQL container if it doesn't already exist
          if ! docker ps -a | grep postgres; then
            echo "Creating the PostgreSQL container..."
            docker run -d -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=postgres postgres
            sleep 20
            echo "PostgreSQL container created successfully."
          fi
          # Start the PostgreSQL server if it's not running
          if ! docker ps | grep postgres; then
            echo "Starting the PostgreSQL server..."
            docker start postgres
            sleep 20
            echo "PostgreSQL server started successfully."
          fi

          # Create a new database 'testdb'
          docker exec -i postgres psql -U postgres -c "CREATE DATABASE testdb;"
          echo "Database created successfully!"
          # Grant all privileges to postgres user
          docker exec -i postgres psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE testdb TO postgres;"
          echo "Database privileges granted successfully!"
          # Change the password for role postgres
          docker exec -i postgres psql -U postgres -c "ALTER USER postgres WITH PASSWORD 'postgres';"
          echo "Password for role 'postgres' changed successfully!"


 
